import { useEffect, useRef, useState } from 'react';

type IconName = 'grid' | 'rocket' | 'server' | 'terminal' | 'book' | 'help' | 'arrow' | 'chevron' | 'check' | 'copy' | 'search' | 'close' | 'external' | 'folder' | 'code' | 'shield' | 'clock' | 'download' | 'settings' | 'refresh' | 'menu' | 'layers' | 'info';
function Icon({ name, size = 20, className = '' }: { name: IconName; size?: number; className?: string }) {
  const paths: Record<IconName, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,
    rocket: <><path d="M14 5c3-3 7-2 7-2s1 4-2 7l-7 7-5-5 7-7Z"/><circle cx="16" cy="8" r="1.5"/><path d="m8 11-4 1-2 4 5-1M13 16l-1 4-4 2 1-5M5 18l-2 3"/></>,
    server: <><rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/><path d="M7 6.5h.01M7 17.5h.01M11 6.5h6M11 17.5h6"/></>,
    terminal: <><rect x="3" y="4" width="18" height="16" rx="3"/><path d="m7 9 3 3-3 3M13 15h4"/></>,
    book: <><path d="M12 5v15M12 5C9 3 5 3 2 4v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-3-1-7-1-10 1Z"/></>,
    help: <><circle cx="12" cy="12" r="9"/><path d="M9.5 9a2.5 2.5 0 0 1 5 .5c0 2-2.5 2-2.5 4M12 17h.01"/></>,
    arrow: <><path d="M4 12h16m-6-6 6 6-6 6"/></>,
    chevron: <path d="m9 5 7 7-7 7"/>,
    check: <path d="m5 12 4 4L19 6"/>,
    copy: <><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></>,
    search: <><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,
    close: <path d="m6 6 12 12M6 18 18 6"/>,
    external: <><path d="M14 3h7v7m0-7L10 14M10 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-5"/></>,
    folder: <path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/>,
    code: <><path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-16-2 20"/></>,
    shield: <><path d="m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Z"/><path d="m8 12 3 3 5-6"/></>,
    clock: <><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,
    download: <><path d="M12 3v12m-5-5 5 5 5-5M4 15v5h16v-5"/></>,
    settings: <><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/></>,
    refresh: <><path d="M20 7v5h-5M4 17v-5h5M5 7a8 8 0 0 1 13-2l2 3M4 16l2 3a8 8 0 0 0 13-2"/></>,
    menu: <path d="M4 6h16M4 12h16M4 18h16"/>,
    layers: <><path d="m12 3 10 5-10 5L2 8l10-5Zm-10 9 10 5 10-5M2 16l10 5 10-5"/></>,
    info: <><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true">{paths[name]}</svg>;
}
const steps = [
  { title: 'Подготовка', label: 'Подготовим фронтэнд', icon: 'folder' as IconName, time: '3 минуты' },
  { title: 'Подключение', label: 'Свяжем фронтэнд и API', icon: 'layers' as IconName, time: '5 минут' },
  { title: 'Сервис systemd', label: 'Настроим сервисы', icon: 'server' as IconName, time: '5 минут' },
  { title: 'Автозапуск', label: 'Включим автозапуск', icon: 'refresh' as IconName, time: '2 минуты' },
  { title: 'Проверка', label: 'Проверим после перезагрузки', icon: 'check' as IconName, time: '3 минуты' },
];
const questions = [
  { q: 'Страница не открывается', a: 'Проверьте, что вводите http://localhost:3000, а не https. Выполните sudo nginx -t, затем systemctl status nginx --no-pager. Если порт занят, команда sudo ss -ltnp показывает, какой процесс его использует. Остановите старый dev-сервер перед запуском Nginx.' },
  { q: 'Фронтэнд работает, но ответов от AI нет', a: 'Откройте инструменты разработчика браузера (F12), вкладку Network. Ошибка 502 у /api означает, что Nginx не может подключиться к бэкенду. Проверьте его порт, команду запуска и журнал: journalctl -u ai-backend -n 50 --no-pager. Также проверьте systemctl status ollama. Для потоковых ответов в конфигурации ниже уже отключена буферизация.' },
  { q: 'Ошибка 203/EXEC или сервис постоянно перезапускается', a: 'В ExecStart должен быть абсолютный путь к существующему исполняемому файлу. systemd не загружает ваш .bashrc и не активирует venv или nvm. Проверьте путь командой ls -l, используйте полный путь к Python из виртуального окружения или к Node. После изменения unit-файла выполните sudo systemctl daemon-reload и перезапустите сервис.' },
  { q: 'Как обновлять фронтэнд?', a: 'После изменения кода перейдите в /home/beluga/ai-multi-agent/frontend, выполните npm run build, а затем sudo cp -a dist/. /srv/ai-multi-agent/frontend/. Обновите страницу браузера с Ctrl + Shift + R. Перезапуск Nginx для обновления статических файлов не требуется.' },
  { q: 'Как отключить автозапуск?', a: 'Команда sudo systemctl disable --now ai-backend отключает и останавливает бэкенд. Для фронтэнда используйте sudo systemctl disable --now nginx, только если Nginx не обслуживает другие сайты. Ollama эти команды не затрагивают.' },
];
function CodeBlock({ code, label = 'ТЕРМИНАЛ', file = false }: { code: string; label?: string; file?: boolean }) {
  const [copied, setCopied] = useState(false);
  async function copy() {
    try { await navigator.clipboard.writeText(code); setCopied(true); setTimeout(() => setCopied(false), 2000); }
    catch { setCopied(false); window.prompt('Скопируйте команду:', code); }
  }
  return <div className={`code-block ${file ? 'file-code' : ''}`}><div className="code-head"><span><Icon name={file ? 'code' : 'terminal'} size={14}/>{label}</span><button onClick={copy} title="Скопировать" aria-label="Скопировать команды"><Icon name={copied ? 'check' : 'copy'} size={15}/>{copied ? 'Скопировано' : 'Копировать'}</button></div><pre><code>{code.split('\n').map((line, i) => <span className={`code-line ${line.startsWith('#') ? 'comment-line' : ''}`} key={i}>{!file && !line.startsWith('#') && line.length > 0 && <span className="prompt">$ </span>}{line || ' '}{'\n'}</span>)}</code></pre></div>;
}
function Note({ children, title, warning = false }: { children: React.ReactNode; title?: string; warning?: boolean }) {
  return <div className={`note ${warning ? 'warning' : ''}`}><Icon name={warning ? 'info' : 'shield'} size={19}/><div>{title && <strong>{title}</strong>}<p>{children}</p></div></div>;
}
function App() {
  const [activeStep, setActiveStep] = useState(0);
  const [completed, setCompleted] = useState<number[]>(() => { try { return JSON.parse(localStorage.getItem('ai-guide-progress') || '[]'); } catch { return []; } });
  const [view, setView] = useState('guide');
  const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [root, setRoot] = useState('/home/beluga/ai-multi-agent');
  const [port, setPort] = useState('8000');
  const [draftRoot, setDraftRoot] = useState(root);
  const [draftPort, setDraftPort] = useState(port);
  const [settingsError, setSettingsError] = useState('');
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [mobileNav, setMobileNav] = useState(false);
  const [toast, setToast] = useState('');
  const guideRef = useRef<HTMLDivElement>(null);
  useEffect(() => { localStorage.setItem('ai-guide-progress', JSON.stringify(completed)); }, [completed]);
  useEffect(() => {
    function key(e: KeyboardEvent) { if ((e.ctrlKey || e.metaKey) && e.key === 'k') { e.preventDefault(); setSearchOpen(s => !s); } if (e.key === 'Escape') { setSearchOpen(false); setSettingsOpen(false); setMobileNav(false); } }
    window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key);
  }, []);
  useEffect(() => { if (toast) { const t = setTimeout(() => setToast(''), 3500); return () => clearTimeout(t); } }, [toast]);
  const frontend = `${root}/frontend`;
  const nginxConfig = `server {\n    listen 127.0.0.1:3000;\n    server_name localhost;\n    root /srv/ai-multi-agent/frontend;\n    index index.html;\n\n    location / {\n        try_files $uri $uri/ /index.html;\n    }\n\n    location /api/ {\n        proxy_pass http://127.0.0.1:${port};\n        proxy_http_version 1.1;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_buffering off;\n        proxy_read_timeout 300s;\n    }\n}`;
  const serviceConfig = `[Unit]\nDescription=AI Multi-Agent Backend\nAfter=network.target ollama.service\nWants=ollama.service\n\n[Service]\nType=simple\nUser=beluga\nWorkingDirectory=${root}\n# EXAMPLE: replace with your verified backend command\nExecStart=${root}/.venv/bin/python -m uvicorn main:app --host 127.0.0.1 --port ${port}\nRestart=on-failure\nRestartSec=5\nEnvironment=PYTHONUNBUFFERED=1\n\n[Install]\nWantedBy=multi-user.target`;
  function navigate(next: string) { setView(next); setMobileNav(false); window.scrollTo({ top: 0, behavior: 'smooth' }); }
  function goStep(n: number, scroll = true) { setActiveStep(n); setView('guide'); if (scroll) setTimeout(() => guideRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50); }
  function finishStep() { setCompleted(old => [...new Set([...old, activeStep])]); if (activeStep < 4) goStep(activeStep + 1); else setToast('Все этапы отмечены. Ваше руководство пройдено!'); }
  function downloadConfigs() {
    const text = `AI MULTI-AGENT — ЛОКАЛЬНАЯ УСТАНОВКА\n\nUbuntu / Debian. Следуйте шагам руководства.\nКоманда ExecStart — пример для FastAPI, замените её на вашу рабочую команду.\n\n1. /etc/nginx/sites-available/ai-frontend\n\n${nginxConfig}\n\n2. /etc/systemd/system/ai-backend.service\n\n${serviceConfig}\n\n3. Автозапуск после проверки конфигурации\n\nsudo nginx -t\nsudo systemctl daemon-reload\nsudo systemctl enable --now nginx\nsudo systemctl reload nginx\n# Только если настроен новый ai-backend.service:\nsudo systemctl enable --now ai-backend\n`;
    const url = URL.createObjectURL(new Blob([text], { type: 'text/plain;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'ai-multi-agent-setup.txt'; a.click(); URL.revokeObjectURL(url); setToast('Конфигурации и команды скачаны');
  }
  const searchResults = [...steps.map((s, i) => ({ title: s.label, detail: `Шаг ${i + 1} · ${s.time}`, run: () => goStep(i) })), ...questions.map((q, i) => ({ title: q.q, detail: 'Помощь и решение проблем', run: () => { navigate('help'); setOpenFaq(i); } }))].filter(r => `${r.title} ${r.detail}`.toLowerCase().includes(query.toLowerCase()));
  function renderStep() {
    if (activeStep === 0) return <>
      <p className="step-intro">Сначала проверим окружение и соберём готовую версию интерфейса. Все команды выполняйте в терминале на вашем ПК.</p>
      <div className="instruction"><span className="instruction-num">1.1</span><div><h3>Откройте папку фронтэнда</h3><p>Нажмите <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>, чтобы открыть терминал, и вставьте команду:</p></div></div>
      <CodeBlock code={`cd ${frontend}`} />
      <div className="instruction"><span className="instruction-num">1.2</span><div><h3>Проверьте Node.js и установите зависимости</h3><p>Для Vite 7 нужен Node.js 20.19+ или 22.12+. Выполняйте команды по одной. Продолжайте, только если предыдущая завершилась без ошибок.</p></div></div>
      <CodeBlock code={'node --version\nnpm --version\nnpm install'} />
      <Note title="Установка выполняется один раз">Не запускайте npm через sudo. Если Node.js не найден, установите актуальную LTS-версию по <a href="https://nodejs.org/en/download" target="_blank" rel="noreferrer">официальной инструкции Node.js</a>, затем снова откройте терминал.</Note>
      <div className="instruction"><span className="instruction-num">1.3</span><div><h3>Соберите и разместите фронтэнд</h3><p>Команда build создаст папку dist. Скопируем её содержимое в отдельную папку, доступную Nginx, — домашний каталог открывать для всех не нужно.</p></div></div>
      <CodeBlock code={'npm run build\nsudo mkdir -p /srv/ai-multi-agent/frontend\nsudo cp -a dist/. /srv/ai-multi-agent/frontend/\nsudo find /srv/ai-multi-agent/frontend -type d -exec chmod 755 {} \\;\nsudo find /srv/ai-multi-agent/frontend -type f -exec chmod 644 {} \\;'} />
      <p className="small-text">Ожидаемый результат: сборка завершилась без ошибок, в /srv/ai-multi-agent/frontend есть index.html. Если build отсутствует, проверьте scripts в package.json вашего проекта.</p>
    </>;
    if (activeStep === 1) return <>
      <p className="step-intro">Nginx будет отдавать интерфейс на localhost:3000 и передавать запросы /api/ вашему бэкенду. Это позволяет использовать один адрес без лишних настроек CORS.</p>
      <Note warning title="Проверьте порт и маршруты API">Порт {port} — пример, а не обнаруженная настройка. Укажите реальный порт в «Вашем окружении». Ниже предполагается, что маршруты бэкенда начинаются с /api/. Ollama на 11434 — не ваш бэкенд.</Note>
      <div className="instruction"><span className="instruction-num">2.1</span><div><h3>Укажите относительный адрес API</h3><p>В настройках вашего фронтэнда замените адрес API на /api. Название переменной зависит от проекта: VITE_API_URL — только распространённый пример. Найдите реальное имя в исходном коде. После изменения .env повторите сборку и копирование из шага 1.3.</p></div></div>
      <CodeBlock code={'# Пример .env.production, если код использует эту переменную\nVITE_API_URL=/api'} label=".ENV.PRODUCTION · ПРИМЕР" file />
      <div className="instruction"><span className="instruction-num">2.2</span><div><h3>Установите Nginx и создайте конфигурацию</h3><p>Команды рассчитаны на Ubuntu / Debian. sudo попросит пароль пользователя: при вводе символы не отображаются — это нормально.</p></div></div>
      <CodeBlock code={'sudo apt update\nsudo apt install nginx\nsudo nano /etc/nginx/sites-available/ai-frontend'} />
      <p>Вставьте следующий текст в редактор:</p><CodeBlock code={nginxConfig} label="/ETC/NGINX/SITES-AVAILABLE/AI-FRONTEND" file />
      <Note title="Как сохранить файл в nano">Нажмите Ctrl + O, затем Enter для подтверждения имени файла. Нажмите Ctrl + X, чтобы выйти. Здесь и далее это одинаковая последовательность для всех файлов.</Note>
      <p className="small-text">proxy_pass без завершающего слеша сохраняет /api/ в пути запроса. Если бэкенд ожидает /chat вместо /api/chat, добавьте слеш после порта: http://127.0.0.1:{port}/. Для WebSocket нужны отдельные Upgrade-заголовки; эта конфигурация рассчитана на HTTP и SSE.</p>
      <div className="instruction"><span className="instruction-num">2.3</span><div><h3>Подключите сайт и проверьте синтаксис</h3><p>Не меняйте другие конфигурации, если Nginx уже используется. На новой установке можно отключить стандартный сайт, чтобы он не слушал внешний порт 80.</p></div></div>
      <CodeBlock code={'sudo ln -sfn /etc/nginx/sites-available/ai-frontend /etc/nginx/sites-enabled/ai-frontend\n# Только если стандартный сайт вам не нужен:\nsudo rm -f /etc/nginx/sites-enabled/default\nsudo nginx -t'} />
      <p className="small-text">Должны появиться сообщения syntax is ok и test is successful. Если порт 3000 занят старым dev-сервером, завершите его через Ctrl + C в его терминале.</p>
    </>;
    if (activeStep === 2) return <>
      <p className="step-intro">systemd — встроенный менеджер сервисов Linux. Он запускает процессы при включении компьютера, без открытого терминала и входа пользователя.</p>
      <Note title="Для фронтэнда сервис уже готов">При установке Nginx создаётся nginx.service. Отдельный ai-frontend.service не нужен: фронтэнд — это файлы, которые отдаёт Nginx. Не используйте npm run dev или vite preview для постоянного запуска.</Note>
      <div className="instruction"><span className="instruction-num">3.1</span><div><h3>Проверьте существующие сервисы</h3><p>Ollama у вас уже добавлена в автозагрузку — переустанавливать её не нужно. Если бэкенд тоже уже работает как сервис, пропустите создание нового и используйте его настоящее имя в следующих командах.</p></div></div>
      <CodeBlock code={'systemctl status ollama --no-pager\nsystemctl cat nginx\nsystemctl list-unit-files --type=service | grep -E "ai|agent|ollama|nginx"'} />
      <div className="instruction"><span className="instruction-num">3.2</span><div><h3>При необходимости создайте сервис бэкенда</h3><p>В вашем сообщении нет команды запуска бэкенда. Поэтому ниже — шаблон для Python / FastAPI, а не универсальная команда. Сначала убедитесь, что ваша обычная команда запуска работает из папки {root}.</p></div></div>
      <CodeBlock code={'sudo nano /etc/systemd/system/ai-backend.service'} />
      <Note warning title="Обязательно замените ExecStart">Пример использует .venv/bin/python и main:app. Подставьте ваш реальный исполняемый файл, модуль и аргументы. Для Node.js используйте абсолютный путь к node и серверному файлу. Не создавайте второй сервис, если бэкенд уже запускается автоматически.</Note>
      <CodeBlock code={serviceConfig} label="AI-BACKEND.SERVICE · ШАБЛОН" file />
      <div className="explain-list"><p><code>User</code><span>Запуск от пользователя beluga, а не от root.</span></p><p><code>WorkingDirectory</code><span>Папка бэкенда. Полный путь, без ~ и команды cd.</span></p><p><code>ExecStart</code><span>Ваша проверенная команда запуска с абсолютным путём.</span></p><p><code>Restart</code><span>Перезапуск через 5 секунд при аварийном завершении.</span></p></div>
      <p className="small-text">systemd не читает .bashrc и не активирует виртуальное окружение. Если приложению нужны переменные окружения, добавьте Environment=ИМЯ=значение или EnvironmentFile с абсолютным путём к отдельному файлу формата KEY=value. Не размещайте секреты во фронтэнде. After= задаёт порядок старта, но не гарантирует готовность API Ollama — бэкенду могут понадобиться повторные попытки подключения.</p>
    </>;
    if (activeStep === 3) return <>
      <p className="step-intro">Теперь зарегистрируем изменения и попросим systemd запускать сервисы при каждой загрузке компьютера.</p>
      <div className="instruction"><span className="instruction-num">4.1</span><div><h3>Включите фронтэнд</h3><p>Сначала проверьте конфигурацию. enable добавляет сервис в автозагрузку, --now запускает его сейчас, а reload применяет новый сайт к уже работающему Nginx.</p></div></div>
      <CodeBlock code={'sudo nginx -t\nsudo systemctl daemon-reload\nsudo systemctl enable --now nginx\nsudo systemctl reload nginx'} />
      <div className="instruction"><span className="instruction-num">4.2</span><div><h3>Включите бэкенд, если создали его сервис</h3><p>Выполните только после замены ExecStart и проверки команды запуска. Если сервис уже существовал под другим именем, используйте это имя вместо ai-backend.</p></div></div>
      <CodeBlock code={'sudo systemctl enable --now ai-backend\nsystemctl status ai-backend --no-pager'} />
      <Note title="Что должно появиться в терминале">Active: active (running) означает, что процесс запущен. Это ещё не проверка работоспособности API. Если видите failed, не перезагружайте ПК — сначала откройте журнал ошибок.</Note>
      <CodeBlock code={'journalctl -u ai-backend -n 50 --no-pager\nsystemctl is-enabled nginx\nsystemctl is-enabled ollama'} />
      <p className="small-text">Для автозапуска ожидается enabled. Если Ollama уже включена, ничего менять не нужно. Если нет — sudo systemctl enable --now ollama.</p>
    </>;
    return <>
      <p className="step-intro">Финальный этап: убедимся, что открывается не только страница, но и вся цепочка — фронтэнд, бэкенд и Ollama.</p>
      <div className="instruction"><span className="instruction-num">5.1</span><div><h3>Откройте интерфейс</h3><p>Откройте адрес ниже в браузере на том же компьютере. Отправьте тестовое сообщение и дождитесь ответа модели. Добавьте страницу в закладки с помощью Ctrl + D.</p></div></div>
      <a className="localhost-link" href="http://localhost:3000" target="_blank" rel="noreferrer"><span><Icon name="grid"/>http://localhost:3000</span><Icon name="external" size={18}/></a>
      <CodeBlock code={'curl -I http://127.0.0.1:3000\ncurl http://127.0.0.1:11434/api/tags'} />
      <p className="small-text">Первая команда должна вернуть HTTP 200, вторая — JSON со списком моделей Ollama. Маршрут проверки бэкенда зависит от вашего проекта; проверьте его через Network в браузере или используйте документированный health endpoint.</p>
      <div className="instruction"><span className="instruction-num">5.2</span><div><h3>Перезагрузите компьютер</h3><p>Сохраните открытые документы, закройте приложения и только затем выполните команду. Компьютер сразу начнёт перезагрузку.</p></div></div>
      <CodeBlock code={'sudo reboot'} />
      <div className="instruction"><span className="instruction-num">5.3</span><div><h3>Проверьте запуск без терминала</h3><p>После загрузки подождите несколько секунд, откройте закладку и отправьте сообщение. Никакие npm-команды вводить больше не нужно.</p></div></div>
      <Note title="Готово. Теперь всё запускается само">Nginx отдаёт фронтэнд, systemd поддерживает бэкенд, Ollama обрабатывает запросы. Адрес 127.0.0.1 доступен только на вашем ПК — не открывайте порты на роутере для этой настройки.</Note>
      <p className="small-text">Если после перезагрузки что-то не работает, посмотрите systemctl status nginx ai-backend ollama --no-pager и раздел «Помощь». Эта страница не имеет доступа к вашему systemd: проверку необходимо выполнить на вашем ПК.</p>
    </>;
  }
  return <div className="app-shell">
    {mobileNav && <div className="nav-backdrop" onClick={() => setMobileNav(false)}/>}
    <aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}>
      <a href="#" className="brand" onClick={e => { e.preventDefault(); navigate('guide'); }}><span className="brand-symbol"><span/><span/><span/></span><span>multi<span className="brand-light">agent</span><small>YOUR LOCAL AI WORKSPACE</small></span></a>
      <button className="workspace" onClick={() => { setDraftRoot(root); setDraftPort(port); setSettingsOpen(true); }}><span className="workspace-icon"><Icon name="layers" size={19}/></span><span><strong>AI Multi-Agent</strong><small><i/>Локальный проект</small></span><Icon name="chevron" size={14}/></button>
      <div className="nav-label">РАБОЧЕЕ ПРОСТРАНСТВО</div>
      <nav className="main-nav">
        <button className={view === 'overview' ? 'active' : ''} onClick={() => navigate('overview')}><Icon name="grid"/><span>Обзор проекта</span></button>
        <button className={view === 'guide' ? 'active' : ''} onClick={() => navigate('guide')}><Icon name="rocket"/><span>Установка и запуск</span><span className="active-dot"/></button>
        <button className={view === 'services' ? 'active' : ''} onClick={() => navigate('services')}><Icon name="server"/><span>Сервисы</span><span className="nav-count">3</span></button>
        <button className={view === 'commands' ? 'active' : ''} onClick={() => navigate('commands')}><Icon name="terminal"/><span>Полезные команды</span></button>
      </nav>
      <div className="nav-label resources-label">РЕСУРСЫ</div>
      <nav className="main-nav"><button onClick={() => { navigate('guide'); goStep(0, false); }}><Icon name="book"/><span>Документация</span><Icon name="external" size={13}/></button><button className={view === 'help' ? 'active' : ''} onClick={() => navigate('help')}><Icon name="help"/><span>Помощь</span></button></nav>
      <div className="sidebar-bottom"><div className="local-card"><span className="local-shield"><Icon name="shield" size={20}/></span><h4>Ваш AI. Ваши правила.</h4><p>Без облака. Без подписок.<br/>Всё на вашем компьютере.</p><span className="local-tag"><i/>LOCAL FIRST</span></div><div className="sidebar-footer"><span className="avatar">B</span><div><strong>beluga</strong><small>Локальное окружение</small></div><button aria-label="Настройки окружения" onClick={() => { setDraftRoot(root); setDraftPort(port); setSettingsOpen(true); }}><Icon name="settings" size={18}/></button></div></div>
    </aside>
    <div className="main-shell">
      <header className="topbar"><div className="topbar-left"><button className="mobile-menu icon-button" onClick={() => setMobileNav(!mobileNav)} aria-label="Открыть меню"><Icon name="menu"/></button><span>Документация</span><span className="header-divider"/><span className="header-subtitle">Начните с простого</span></div><div className="topbar-right"><button className="search-trigger" onClick={() => setSearchOpen(true)}><Icon name="search" size={17}/><span>Поиск по руководству</span><kbd>Ctrl K</kbd></button><span className="version">v1.0</span></div></header>
      <main className="main-content">
        <div className="breadcrumb"><span>AI Multi-Agent</span><Icon name="chevron" size={12}/><span>{view === 'guide' ? 'Установка и запуск' : view === 'overview' ? 'Обзор проекта' : view === 'services' ? 'Сервисы' : view === 'commands' ? 'Полезные команды' : 'Помощь'}</span></div>
        {view === 'guide' && <>
          <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> НАСТРОИЛИ ОДИН РАЗ — ПОЛЬЗУЕТЕСЬ ВСЕГДА</div><h1>Ваш локальный AI.<br/><span>Всегда готов к работе.</span></h1><p>Подключите фронтэнд и настройте автозапуск.<br/>После перезагрузки — просто откройте браузер.</p><div className="hero-meta"><span><Icon name="clock" size={15}/>15–20 минут</span><span><Icon name="terminal" size={15}/>Ubuntu / Debian</span><span><Icon name="check" size={15}/>Подойдёт новичкам</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="art-dots"/><div className="floating-icon float-code"><Icon name="code" size={25}/></div><div className="art-window"><div className="art-window-bar"><span className="window-dots"><i/><i/><i/></span><span>localhost:3000</span><Icon name="shield" size={11}/></div><div className="art-window-body"><span className="art-main-icon"><Icon name="terminal" size={34}/></span><div className="art-code-lines"><i/><i/><i/></div><span className="art-ready"><i/>Всё готово к запуску</span></div></div><div className="floating-icon float-server"><Icon name="server" size={25}/><span className="tiny-status"/></div><span className="art-spark spark-one">+</span><span className="art-spark spark-two">+</span></div></section>
          <div className="benefits"><div><span className="benefit-icon"><Icon name="refresh" size={20}/></span><div><strong>Запуск вместе с системой</strong><p>Никаких команд после перезагрузки</p></div></div><div><span className="benefit-icon"><Icon name="shield" size={20}/></span><div><strong>Полностью локально</strong><p>Ваши данные остаются на вашем ПК</p></div></div><div><span className="benefit-icon"><Icon name="layers" size={20}/></span><div><strong>Всё работает вместе</strong><p>Фронтэнд + бэкенд + Ollama</p></div></div></div>
          <div className="guide-section" ref={guideRef}><div className="section-heading"><div><h2>Настроим автозапуск <span>5 шагов</span></h2><p>Следуйте инструкции по порядку. Мы рядом на каждом шаге.</p></div><button className="text-button download-button" onClick={downloadConfigs}><Icon name="download" size={16}/>Скачать конфиги</button></div>
          <div className="stepper">{steps.map((s, i) => <button key={s.title} className={`step-tab ${activeStep === i ? 'selected' : ''} ${completed.includes(i) ? 'completed' : ''}`} onClick={() => goStep(i, false)}><span className="step-number">{completed.includes(i) ? <Icon name="check" size={15}/> : `0${i + 1}`}</span><span>{s.title}</span>{i < 4 && <Icon className="step-arrow" name="chevron" size={13}/>}</button>)}</div>
          <div className="guide-layout"><article className="step-card"><div className="step-card-heading"><span className="step-title-icon"><Icon name={steps[activeStep].icon} size={22}/></span><div><span className="step-overline">ШАГ {activeStep + 1} ИЗ 5</span><h2>{steps[activeStep].label}</h2></div><span className="step-time"><Icon name="clock" size={14}/>{steps[activeStep].time}</span></div>{renderStep()}<div className="step-actions"><button className={`done-toggle ${completed.includes(activeStep) ? 'is-done' : ''}`} onClick={() => setCompleted(old => old.includes(activeStep) ? old.filter(n => n !== activeStep) : [...old, activeStep])}><span>{completed.includes(activeStep) && <Icon name="check" size={12}/>}</span>Я выполнил этот шаг</button><button className="primary-button" onClick={finishStep}>{activeStep === 4 ? 'Завершить' : 'Следующий шаг'}<Icon name="arrow" size={17}/></button></div></article>
          <aside className="guide-aside"><div className="environment-card"><div className="aside-card-heading"><h3><Icon name="settings" size={17}/>Ваше окружение</h3><button title="Изменить окружение" aria-label="Изменить окружение" onClick={() => { setDraftRoot(root); setDraftPort(port); setSettingsOpen(true); }}><Icon name="settings" size={16}/></button></div><p className="aside-description">Используем пути вашего проекта</p><div className="path-item"><span><Icon name="code" size={14}/>Фронтэнд</span><code>{frontend}/</code></div><div className="path-item"><span><Icon name="server" size={14}/>Бэкенд</span><code>{root}/</code></div><div className="environment-footer"><span className="linux-icon">◈</span>Linux<span>systemd</span></div></div>
          <div className="connection-card"><h3>Как это будет работать</h3><div className="connection-node"><span className="node-icon"><Icon name="grid" size={17}/></span><div><strong>Браузер</strong><small>localhost:3000</small></div><span className="node-badge">UI</span></div><div className="connector"><span/>Nginx · /api</div><div className="connection-node"><span className="node-icon"><Icon name="server" size={17}/></span><div><strong>Бэкенд</strong><small>localhost:{port} <em>пример</em></small></div><span className="node-badge">API</span></div><div className="connector"><span/>Локальный запрос</div><div className="connection-node"><span className="node-icon"><Icon name="layers" size={17}/></span><div><strong>Ollama</strong><small>localhost:11434</small></div><span className="ollama-dot"/></div><p className="diagram-note"><Icon name="info" size={13}/>Схема, не мониторинг сервисов</p></div>
          <div className="help-card"><span><Icon name="help" size={20}/></span><div><h3>Что-то пошло не так?</h3><p>Разберём частые ошибки<br/>и поможем найти решение.</p><button className="text-button" onClick={() => navigate('help')}>Открыть помощь<Icon name="arrow" size={15}/></button></div></div>
          <div className="progress-card"><div><span>Ваш прогресс</span><strong>{completed.length} из 5</strong></div><div className="progress-track"><span style={{ width: `${completed.length * 20}%` }}/></div><small>Сохраняется в этом браузере</small></div></aside></div></div>
        </>}
        {view === 'overview' && <><div className="page-heading"><span className="eyebrow">ВАШЕ РАБОЧЕЕ ПРОСТРАНСТВО</span><h1>Всё начинается локально.</h1><p>Три компонента. Один интерфейс. Полный контроль над вашим AI.</p></div><div className="overview-grid">{[{ icon: 'code' as IconName, title: 'Фронтэнд', text: 'Интерфейс React, собранный Vite. Nginx отдаёт файлы и проксирует запросы API.', path: frontend }, { icon: 'server' as IconName, title: 'Бэкенд', text: 'Логика агентов и связь с моделями. Команду запуска нужно проверить в вашем проекте.', path: root }, { icon: 'layers' as IconName, title: 'Ollama', text: 'Локальное выполнение AI-моделей. По вашему сообщению, автозапуск уже настроен.', path: 'http://localhost:11434' }].map((x, i) => <div className="overview-card" key={x.title}><span className="overview-icon"><Icon name={x.icon} size={25}/></span><span className="card-index">0{i + 1}</span><h2>{x.title}</h2><p>{x.text}</p><code>{x.path}</code></div>)}</div><div className="overview-cta"><div><h2>Пусть система запускается сама</h2><p>Пройдите 5 шагов — и больше не запускайте фронтэнд вручную.</p></div><button className="primary-button" onClick={() => navigate('guide')}>Перейти к настройке<Icon name="arrow" size={18}/></button></div><Note title="Это руководство, а не удалённый терминал">Команды нужно выполнять на вашем Linux-компьютере. Страница не подключена к системным сервисам и не может проверить их реальное состояние.</Note></>}
        {view === 'services' && <><div className="page-heading"><span className="eyebrow">УПРАВЛЕНИЕ ОКРУЖЕНИЕМ</span><h1>Каждый сервис на своём месте.</h1><p>Назначение компонентов и команды для проверки их состояния.</p></div><Note title="Статусы проверяются на вашем ПК">Мы не показываем выдуманные показатели доступности. Скопируйте команду соответствующего сервиса и выполните её в терминале.</Note><div className="service-list">{[{ name: 'Nginx', unit: 'nginx', port: '3000', icon: 'grid' as IconName, description: 'Раздаёт собранный фронтэнд и передаёт /api/ бэкенду.' }, { name: 'AI Backend', unit: 'ai-backend', port, icon: 'server' as IconName, description: 'Обрабатывает запросы интерфейса. Имя сервиса и порт — из примера руководства.' }, { name: 'Ollama', unit: 'ollama', port: '11434', icon: 'layers' as IconName, description: 'Запускает языковые модели локально. Автозагрузка уже настроена вами.' }].map(s => <article className="service-card" key={s.unit}><div className="service-title"><span className="overview-icon"><Icon name={s.icon}/></span><div><h2>{s.name}</h2><p>{s.description}</p></div><span className="service-port">:{s.port}</span></div><CodeBlock code={`systemctl status ${s.unit} --no-pager\nsystemctl is-enabled ${s.unit}\njournalctl -u ${s.unit} -n 30 --no-pager`} /></article>)}</div></>}
        {view === 'commands' && <><div className="page-heading"><span className="eyebrow">ПОД РУКОЙ</span><h1>Меньше поиска. Больше дела.</h1><p>Команды для ежедневной работы с вашим локальным окружением.</p></div><div className="commands-grid">{[{ title: 'Проверить все сервисы', text: 'ai-backend — имя из нашего шаблона. Замените, если у вас другое.', code: 'systemctl status nginx ai-backend ollama --no-pager' }, { title: 'Посмотреть журнал бэкенда', text: 'Следить за новыми записями в реальном времени. Ctrl + C — выход.', code: 'journalctl -u ai-backend -f' }, { title: 'Применить изменения systemd', text: 'После редактирования .service перечитайте конфигурацию и перезапустите процесс.', code: 'sudo systemctl daemon-reload\nsudo systemctl restart ai-backend' }, { title: 'Обновить фронтэнд', text: 'Пересоберите интерфейс и скопируйте результат. Затем обновите вкладку браузера.', code: `cd ${frontend}\nnpm run build\nsudo cp -a dist/. /srv/ai-multi-agent/frontend/` }, { title: 'Проверить занятые порты', text: 'Полезно, если сервис сообщает Address already in use.', code: 'sudo ss -ltnp' }, { title: 'Проверить Nginx', text: 'Выполняйте reload только после успешной проверки nginx -t.', code: 'sudo nginx -t\nsudo systemctl reload nginx' }].map(c => <article className="command-card" key={c.title}><h3>{c.title}</h3><p>{c.text}</p><CodeBlock code={c.code}/></article>)}</div></>}
        {view === 'help' && <><div className="page-heading"><span className="eyebrow">МЫ РЯДОМ</span><h1>Разберёмся вместе.</h1><p>Большинство проблем решаются проверкой команды запуска, порта или журнала.</p></div><div className="help-layout"><div className="faq-list">{questions.map((q, i) => <div className={`faq-item ${openFaq === i ? 'faq-open' : ''}`} key={q.q}><button onClick={() => setOpenFaq(openFaq === i ? null : i)}><span>{q.q}</span><Icon name={openFaq === i ? 'close' : 'chevron'} size={18}/></button>{openFaq === i && <p>{q.a}</p>}</div>)}</div><div className="help-resources"><Icon name="book" size={26}/><h3>Первоисточники</h3><p>Официальная документация, если хочется разобраться глубже.</p><a href="https://vite.dev/guide/static-deploy" target="_blank" rel="noreferrer">Развёртывание Vite<Icon name="external" size={14}/></a><a href="https://nginx.org/en/docs/beginners_guide.html" target="_blank" rel="noreferrer">Nginx для начинающих<Icon name="external" size={14}/></a><a href="https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html" target="_blank" rel="noreferrer">Сервисы systemd<Icon name="external" size={14}/></a></div></div><div className="overview-cta"><div><h2>Вернуться к настройке</h2><p>Ваш прогресс сохранён в этом браузере.</p></div><button className="primary-button" onClick={() => navigate('guide')}>Продолжить<Icon name="arrow" size={17}/></button></div></>}
        <footer className="page-footer"><span><span className="footer-mark">m</span>Создано для вашего локального AI.</span><span><Icon name="shield" size={13}/>Ваш компьютер. Ваши данные.</span></footer>
      </main>
    </div>
    {toast && <div className="toast" role="status"><Icon name="check" size={18}/>{toast}<button aria-label="Закрыть уведомление" onClick={() => setToast('')}><Icon name="close" size={14}/></button></div>}
    {searchOpen && <div className="modal-backdrop" onClick={() => setSearchOpen(false)}><section className="search-modal" role="dialog" aria-modal="true" aria-label="Поиск по руководству" onClick={e => e.stopPropagation()}><div className="search-input-row"><Icon name="search"/><input autoFocus placeholder="Какой шаг или проблему ищем?" value={query} onChange={e => setQuery(e.target.value)}/><button className="icon-button" onClick={() => setSearchOpen(false)} aria-label="Закрыть поиск"><Icon name="close" size={19}/></button></div><div className="search-results"><span className="search-label">{query ? 'РЕЗУЛЬТАТЫ ПОИСКА' : 'БЫСТРЫЙ ПЕРЕХОД'}</span>{searchResults.length ? searchResults.map(r => <button key={r.title} onClick={() => { r.run(); setSearchOpen(false); setQuery(''); }}><span><strong>{r.title}</strong><small>{r.detail}</small></span><Icon name="arrow" size={17}/></button>) : <p className="empty-search">Ничего не найдено. Попробуйте «сервис», «фронтэнд» или «ошибка».</p>}</div><div className="search-bottom"><kbd>Esc</kbd> закрыть поиск</div></section></div>}
    {settingsOpen && <div className="modal-backdrop" onClick={() => setSettingsOpen(false)}><section className="settings-modal" role="dialog" aria-modal="true" aria-labelledby="settings-title" onClick={e => e.stopPropagation()}><div className="settings-heading"><span className="overview-icon"><Icon name="settings" size={22}/></span><button className="icon-button" aria-label="Закрыть настройки" onClick={() => setSettingsOpen(false)}><Icon name="close"/></button></div><h2 id="settings-title">Ваше окружение</h2><p>Пути и порт обновятся во всех командах и скачиваемых конфигурациях. Настройки не изменяют файлы на вашем ПК.</p><form onSubmit={e => { e.preventDefault(); if (!/^\/[a-zA-Z0-9_./-]+$/.test(draftRoot) || draftRoot.includes('..')) { setSettingsError('Укажите абсолютный путь без пробелов и специальных символов.'); return; } if (!/^\d+$/.test(draftPort) || +draftPort < 1024 || +draftPort > 65535 || ['3000', '11434'].includes(draftPort)) { setSettingsError('Укажите порт от 1024 до 65535, кроме 3000 и 11434.'); return; } setRoot(draftRoot.replace(/\/$/, '')); setPort(draftPort); setSettingsError(''); setSettingsOpen(false); setToast('Команды обновлены под ваше окружение'); }}><label>Папка проекта<input autoFocus value={draftRoot} onChange={e => setDraftRoot(e.target.value)} required/></label><label>Порт бэкенда<input value={draftPort} onChange={e => setDraftPort(e.target.value)} inputMode="numeric" required/></label><small>Пользователь systemd в шаблоне — beluga. Если он другой, измените User вручную.</small>{settingsError && <p className="form-error" role="alert">{settingsError}</p>}<button className="primary-button" type="submit">Сохранить настройки<Icon name="check" size={17}/></button></form></section></div>}
  </div>;
}
export default App;
